set(CMAKE_SYSTEM_NAME Linux)

if(NOT DEFINED MOONCHILD_TARGET_ARCH)
    set(MOONCHILD_TARGET_ARCH "LinuxX64")
endif()

# Linux x64
if(MOONCHILD_TARGET_ARCH STREQUAL "LinuxX64")
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
    set(CMAKE_C_COMPILER clang CACHE FILEPATH "" FORCE)
    set(CMAKE_CXX_COMPILER clang++ CACHE FILEPATH "" FORCE)

# Linux AArch64
elseif(MOONCHILD_TARGET_ARCH STREQUAL "LinuxArm64")
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
    set(CMAKE_C_COMPILER clang CACHE FILEPATH "" FORCE)
    set(CMAKE_CXX_COMPILER clang++ CACHE FILEPATH "" FORCE)

    if(NOT CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
        set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu CACHE STRING "" FORCE)
        set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    endif()

else()
    message(FATAL_ERROR "Unsupported Linux target architecture: ${MOONCHILD_TARGET_ARCH}")
endif()
